In [16]:
from keras.models import Sequential,Model
from keras.layers import Dense,Input
from keras.losses import mean_squared_error
import tensorflow as tf

# y_true = tf.Tensor([1])
# y_pred = tf.Tensor([0])
c = tf.constant([1.0])
d = tf.constant([0.0])
# e = tf.matmul(c, d)
e = mean_squared_error(c,d)
with tf.Session() as sess:
    print(e)
    print(e.eval())

Tensor("Mean_7:0", shape=(), dtype=float32)
1.0


In [15]:
import tensorflow as tf
import numpy as np
 
# 建立一个多维数组
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("建立的数组a为：\n", a)
with tf.Session() as sess:
	print("下面把数组a转化为张量：\n")
	tensor_a = tf.convert_to_tensor(a)
	print("转换成的张量为：\n", tensor_a)
	print("下面把张量tensor_a再转化数组：\n")
	a_convert = tensor_a.eval()
	print("转换成的数组为：\n", a_convert)


建立的数组a为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
下面把数组a转化为张量：

转换成的张量为：
 Tensor("Const_10:0", shape=(3, 3), dtype=int32)
下面把张量tensor_a再转化数组：

转换成的数组为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
